
export const fakeInfo = [
    {
        id:'Bike2490GHBk',
        name:'Bike',
        rideShare:'300',
        imgUrl:'https://i.ibb.co/bWTvFgk/bike.png',
        random:3
    },{
        id:'Car434LJD',
        name:'Car',
        rideShare:'400',
        imgUrl:'https://i.ibb.co/vdpSLfP/car.png',
        random:5
    },
    {
        id:'Bus5403TUP',
        name:'Bus',
        rideShare:'220',
        imgUrl:'https://i.ibb.co/Gn1r2cM/bus.png',
        random:7
    },
    {
        id:'Train503HUT',
        name:'Train',
        rideShare:'100',
        imgUrl:'https://i.ibb.co/sKfVBCG/train.png',
        random:1
    }
]